### ISSUE TITLE
Compilation fails with Release target

### ISSUE THREAD

**Issue by mguentner** [vasild/cpp-ipfs-api#1]
When compiling with

```
cmake -DCMAKE_BUILD_TYPE=Release
```

the compilation fails with

```
Scanning dependencies of target ipfs-api
[  5%] Building CXX object CMakeFiles/ipfs-api.dir/src/client.cc.o
[ 10%] Building CXX object CMakeFiles/ipfs-api.dir/src/http/transport-curl.cc.o
/tmp/nix-build-cpp-ipfs-api-2016-11-26.drv-0/cpp-ipfs-api-3b64e6e4520e87f14fee4216b4b5184c6f97a47a-src/src/http/transport-curl.cc: In lambda function:
/tmp/nix-build-cpp-ipfs-api-2016-11-26.drv-0/cpp-ipfs-api-3b64e6e4520e87f14fee4216b4b5184c6f97a47a-src/src/http/transport-curl.cc:293:5: error: 'replace_body' was not declared in this scope
     replace_body = "";
     ^
```

Background:

This happens with the latest commit of cpp-ipfs-api when building for NixOS (currently an [older version is packaged](https://github.com/NixOS/nixpkgs/blob/ab39c292932ae5a5021b852b25db8416c0ac28a0/pkgs/development/libraries/cpp-ipfs-api/default.nix)) and the build system uses the CMake default target `Release` for non-debug builds (`Debug` being the default for debug builds).

**Comment by vasild** [comment]
Fixed, thanks!

**Comment by mguentner** [comment]
Thank you for fixing it so fast. The version in NixOS is now up-to-date:
https://github.com/NixOS/nixpkgs/pull/21640/commits/e9ab1a614f31e4eb61dc864fcfb404eabc28084b
